// College logos mapping
const collegeLogos = {
  'MIT': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/MIT_logo.svg/120px-MIT_logo.svg.png',
  'Stanford': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Signature_of_Stanford_University.svg/200px-Signature_of_Stanford_University.svg.png',
  'Harvard': 'logos/harvard.png',
  'Yale': 'logos/yale.png',
  'Columbia': 'logos/Columbia.png',
  'Brown': 'logos/brown.jpg',
  'Duke': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Duke_Athletics_logo.svg/120px-Duke_Athletics_logo.svg.png',
  'Princeton': 'logos/Princeton.png',
  'Cornell': 'logos/Cornell.png',
  'UPenn': 'logos/Penn.png',
  'Berklee': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Berklee_College_of_Music_logo.svg/120px-Berklee_College_of_Music_logo.svg.png',
  'RISD': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/RISD_coa.svg/120px-RISD_coa.svg.png',
  'Juilliard': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Juilliard_School_logo.svg/120px-Juilliard_School_logo.svg.png',
  'Khan Academy': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Khan_Academy_Logo_2018.svg/120px-Khan_Academy_Logo_2018.svg.png',
  'Google': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/120px-Google_%22G%22_Logo.svg.png',
  'Coursera': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Coursera_logo_2022.svg/120px-Coursera_logo_2022.svg.png',
  'Wharton': 'logos/Penn.png',
  'Parsons': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Parsons_The_New_School_for_Design_logo.svg/120px-Parsons_The_New_School_for_Design_logo.svg.png',
  'Apple': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/120px-Apple_logo_black.svg.png',
  'Girls Who Code': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Girls_Who_Code_logo.svg/120px-Girls_Who_Code_logo.svg.png',
  'Y Combinator': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Y_Combinator_logo.svg/120px-Y_Combinator_logo.svg.png',
  'Babson': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Babson_College_Logo.svg/120px-Babson_College_Logo.svg.png',
  'Northwestern': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Northwestern_University_seal.svg/120px-Northwestern_University_seal.svg.png',
  'Kenyon': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Kenyon_College_seal.svg/120px-Kenyon_College_seal.svg.png',
  'Iowa Writers': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/University_of_Iowa_seal.svg/120px-University_of_Iowa_seal.svg.png',
  'edX': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/EdX_logo.svg/120px-EdX_logo.svg.png',
  'MIT OCW': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/MIT_logo.svg/120px-MIT_logo.svg.png',
  'UC Berkeley': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/University_of_California_Berkeley_seal_2013.svg/120px-University_of_California_Berkeley_seal_2013.svg.png',
  'UCLA': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/UCLA_Bruins_wordmark.svg/120px-UCLA_Bruins_wordmark.svg.png',
  'NYU': 'logos/nyu.jpg',
  'NYU Tisch': 'logos/nyu.jpg',
  'NYU Gallatin': 'logos/nyu.jpg',
  'Carnegie Mellon': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Carnegie_Mellon_seal.svg/120px-Carnegie_Mellon_seal.svg.png',
  'CMU': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Carnegie_Mellon_seal.svg/120px-Carnegie_Mellon_seal.svg.png',
  'CMU S3': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Carnegie_Mellon_seal.svg/120px-Carnegie_Mellon_seal.svg.png',
  'Georgetown': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Georgetown_Athletics_logo.svg/120px-Georgetown_Athletics_logo.svg.png',
  'Georgetown Prep': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Georgetown_Athletics_logo.svg/120px-Georgetown_Athletics_logo.svg.png',
  'Ross Program': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/MIT_logo.svg/120px-MIT_logo.svg.png',
  'Boston University': 'logos/BU.png',
  'Telluride Association': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/MIT_logo.svg/120px-MIT_logo.svg.png',
  'NASA': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/NASA_logo.svg/120px-NASA_logo.svg.png',
  'NASA JSC': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/NASA_logo.svg/120px-NASA_logo.svg.png',
  'Smith College': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Smith_College_seal.svg/120px-Smith_College_seal.svg.png',
  'Stony Brook': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Stony_Brook_Athletics_logo.svg/120px-Stony_Brook_Athletics_logo.svg.png',
  'UC San Diego': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/UCSD_Athletics_logo.svg/120px-UCSD_Athletics_logo.svg.png',
  'Smithsonian': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Smithsonian_Institution_logo.svg/120px-Smithsonian_Institution_logo.svg.png',
  'AMNH': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/American_Museum_of_Natural_History_logo.svg/120px-American_Museum_of_Natural_History_logo.svg.png',
  'Johns Hopkins': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Johns_Hopkins_University_seal.svg/120px-Johns_Hopkins_University_seal.svg.png',
  'JHU': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Johns_Hopkins_University_seal.svg/120px-Johns_Hopkins_University_seal.svg.png',
  'Duke TIP': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Duke_Athletics_logo.svg/120px-Duke_Athletics_logo.svg.png',
  'Oxford': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/University_of_Oxford_crest.svg/120px-University_of_Oxford_crest.svg.png',
  'Cambridge': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/University_of_Cambridge_coat_of_arms.svg/120px-University_of_Cambridge_coat_of_arms.svg.png',
  'LSE': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/London_School_of_Economics_logo.svg/120px-London_School_of_Economics_logo.svg.png',
  'Imperial': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Imperial_College_London_crest.svg/120px-Imperial_College_London_crest.svg.png',
  'ETH Zurich': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/ETH_Zürich_logo.svg/120px-ETH_Zürich_logo.svg.png',
  'UTokyo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/University_of_Tokyo_seal.svg/120px-University_of_Tokyo_seal.svg.png',
  'NUS': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/National_University_of_Singapore_logo.svg/120px-National_University_of_Singapore_logo.svg.png',
  'HKU': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/University_of_Hong_Kong_logo.svg/120px-University_of_Hong_Kong_logo.svg.png',
  'U of T': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/University_of_Toronto_coat_of_arms.svg/120px-University_of_Toronto_coat_of_arms.svg.png',
  'McGill': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/McGill_University_coat_of_arms.svg/120px-McGill_University_coat_of_arms.svg.png',
  'UBC': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/University_of_British_Columbia_seal.svg/120px-University_of_British_Columbia_seal.svg.png',
  'Waterloo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/University_of_Waterloo_seal.svg/120px-University_of_Waterloo_seal.svg.png',
  'Microsoft': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo_%282012%29.svg/120px-Microsoft_logo_%282012%29.svg.png',
  'Meta': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Meta-Logo.svg/120px-Meta-Logo.svg.png',
  'NVIDIA': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/NVIDIA_logo.svg/120px-NVIDIA_logo.svg.png',
  'SpaceX': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/SpaceX_logo_%282020%29.svg/120px-SpaceX_logo_%282020%29.svg.png',
  'Blue Origin': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Blue_Origin_logo.svg/120px-Blue_Origin_logo.svg.png',
  'Stripe': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Stripe_Logo%2C_revised_2016.svg/120px-Stripe_Logo%2C_revised_2016.svg.png',
  'Airbnb': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Airbnb_Logo_Bélo.svg/120px-Airbnb_Logo_Bélo.svg.png',
  'Uber': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Uber_logo_2018.svg/120px-Uber_logo_2018.svg.png',
  'Twitter/X': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/X_logo_2023.svg/120px-X_logo_2023.svg.png',
  'Amazon': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Amazon_logo.svg/120px-Amazon_logo.svg.png',
  'Netflix': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Netflix_2015_logo.svg/120px-Netflix_2015_logo.svg.png',
  'Spotify': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Spotify_logo_without_text.svg/120px-Spotify_logo_without_text.svg.png',
  'Notion': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Notion_app_logo.png/120px-Notion_app_logo.png',
  'Figma': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Figma-logo.svg/120px-Figma-logo.svg.png',
  'JPL': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/JPL_logo.svg/120px-JPL_logo.svg.png',
  'Fermilab': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Fermilab_logo.svg/120px-Fermilab_logo.svg.png',
  'CERN': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/CERN_logo.svg/120px-CERN_logo.svg.png',
  'Peace Corps': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Peace_Corps_logo.svg/120px-Peace_Corps_logo.svg.png',
  'Teach For America': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/TFA_logo.svg/120px-TFA_logo.svg.png',
  'TFA': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/TFA_logo.svg/120px-TFA_logo.svg.png',
  'City Year': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/City_Year_logo.svg/120px-City_Year_logo.svg.png',
  'Global Health Corps': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/GHC_logo.svg/120px-GHC_logo.svg.png',
  'GHC': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/GHC_logo.svg/120px-GHC_logo.svg.png',
  'West Point': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/United_States_Military_Academy_coat_of_arms.svg/120px-United_States_Military_Academy_coat_of_arms.svg.png',
  'Air Force Academy': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/United_States_Air_Force_Aceademy_seal.svg/120px-United_States_Air_Force_Aceademy_seal.svg.png',
  'USAFA': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/United_States_Air_Force_Aceademy_seal.svg/120px-United_States_Air_Force_Aceademy_seal.svg.png',
  'DECA': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/DECA_logo.svg/120px-DECA_logo.svg.png',
  'Science Olympiad': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Science_Olympiad_logo.svg/120px-Science_Olympiad_logo.svg.png',
  'Mathcamp': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/MIT_logo.svg/120px-MIT_logo.svg.png',
  'HCSSiM': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Hampshire_College_seal.svg/120px-Hampshire_College_seal.svg.png',
  'CalArts': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/CalArts_logo.svg/120px-CalArts_logo.svg.png',
  'Pratt': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Pratt_Institute_seal.svg/120px-Pratt_Institute_seal.svg.png',
  'Kellogg': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Kellogg_School_of_Management_logo.svg/120px-Kellogg_School_of_Management_logo.svg.png',
  'Haas': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Haas_School_of_Business_logo.svg/120px-Haas_School_of_Business_logo.svg.png',
  'Michigan Ross': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Ross_School_of_Business_logo.svg/120px-Ross_School_of_Business_logo.svg.png',
  'Tuck': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Tuck_School_of_Business_logo.svg/120px-Tuck_School_of_Business_logo.svg.png',
  'Darden': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Darden_School_of_Business_logo.svg/120px-Darden_School_of_Business_logo.svg.png',
  'Yale Law': 'logos/yale.png',
  'Columbia Business': 'logos/Columbia.png',
  'USC': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/University_of_Southern_California_seal.svg/120px-University_of_Southern_California_seal.svg.png',
  'UC Davis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/UC_Davis_Aggies_logo.svg/120px-UC_Davis_Aggies_logo.svg.png',
  'UCI': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/UCI_Athletics_logo.svg/120px-UCI_Athletics_logo.svg.png',
  'UC Santa Barbara': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/UCSB_Athletics_logo.svg/120px-UCSB_Athletics_logo.svg.png',
  'Arizona State': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Arizona_State_Athletics_logo.svg/120px-Arizona_State_Athletics_logo.svg.png',
  'University of Colorado': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/University_of_Colorado_Boulder_seal.svg/120px-University_of_Colorado_Boulder_seal.svg.png',
  'University of Miami': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Miami_Hurricanes_logo.svg/120px-Miami_Hurricanes_logo.svg.png',
  'University of Denver': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Denver_Pioneers_logo.svg/120px-Denver_Pioneers_logo.svg.png',
  'University of Hawaii': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Hawaii_Rainbow_Warriors_logo.svg/120px-Hawaii_Rainbow_Warriors_logo.svg.png',
  'University of Florida': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Florida_Gators_logo.svg/120px-Florida_Gators_logo.svg.png',
  'Penn State': 'logos/Penn.png',
  'Ohio State': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Ohio_State_Buckeyes_logo.svg/120px-Ohio_State_Buckeyes_logo.svg.png',
  'University of Michigan': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Michigan_Wolverines_logo.svg/120px-Michigan_Wolverines_logo.svg.png',
  'Georgia Tech': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Georgia_Tech_Yellow_Jackets_logo.svg/120px-Georgia_Tech_Yellow_Jackets_logo.svg.png',
  'Virginia Tech': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Virginia_Tech_Hokies_logo.svg/120px-Virginia_Tech_Hokies_logo.svg.png',
  'University of Texas': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/University_of_Texas_at_Austin_seal.svg/120px-University_of_Texas_at_Austin_seal.svg.png',
  'WashU': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Washington_University_in_St_Louis_seal.svg/120px-Washington_University_in_St_Louis_seal.svg.png',
  'Rice': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Rice_Owls_logo.svg/120px-Rice_Owls_logo.svg.png',
  'Dartmouth': 'logos/Dartmouth.png',
  'Williams': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Williams_College_seal.svg/120px-Williams_College_seal.svg.png',
  'Amherst': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Amherst_College_seal.svg/120px-Amherst_College_seal.svg.png',
  'Swarthmore': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Swarthmore_College_seal.svg/120px-Swarthmore_College_seal.svg.png',
  'Middlebury': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Middlebury_College_seal.svg/120px-Middlebury_College_seal.svg.png',
  'Carleton': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Carleton_College_seal.svg/120px-Carleton_College_seal.svg.png',
  'Oberlin': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Oberlin_College_seal.svg/120px-Oberlin_College_seal.svg.png',
  'Vassar': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Vassar_College_seal.svg/120px-Vassar_College_seal.svg.png',
  'Wellesley': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Wellesley_College_seal.svg/120px-Wellesley_College_seal.svg.png',
  'Barnard': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Barnard_College_seal.svg/120px-Barnard_College_seal.svg.png',
  'Bryn Mawr': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Bryn_Mawr_College_seal.svg/120px-Bryn_Mawr_College_seal.svg.png',
  'Interlochen': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Interlochen_Center_for_the_Arts_logo.svg/120px-Interlochen_Center_for_the_Arts_logo.svg.png',
  'SAIC': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/School_of_the_Art_Institute_of_Chicago_seal.svg/120px-School_of_the_Art_Institute_of_Chicago_seal.svg.png',
  'Cooper Union': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Cooper_Union_seal.svg/120px-Cooper_Union_seal.svg.png',
  'SCAD': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/SCAD_Savannah_seal.svg/120px-SCAD_Savannah_seal.svg.png',
  'Ringling': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Ringling_College_of_Art_and_Design_logo.svg/120px-Ringling_College_of_Art_and_Design_logo.svg.png',
  'Full Sail': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Full_Sail_University_logo.svg/120px-Full_Sail_University_logo.svg.png',
  'General Assembly': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/General_Assembly_logo.svg/120px-General_Assembly_logo.svg.png',
  'Google UX': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/120px-Google_%22G%22_Logo.svg.png',
  'AMA': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/American_Marketing_Association_logo.svg/120px-American_Marketing_Association_logo.svg.png',
  'Hootsuite': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Hootsuite_logo.svg/120px-Hootsuite_logo.svg.png',
  'Moz': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Moz_Logo_2019.svg/120px-Moz_Logo_2019.svg.png',
  'Fast.ai': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Fast.ai_logo.svg/120px-Fast.ai_logo.svg.png',
  '(ISC)2': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/ISC2_logo.svg/120px-ISC2_logo.svg.png',
  'AWS': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Amazon_Web_Services_Logo.svg/120px-Logo.svg.png',
  'PMI': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/PMI_logo.svg/120px-PMI_logo.svg.png',
  'SHRM': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/SHRM_logo.svg/120px-SHRM_logo.svg.png',
  'ICF': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/International_Coaching_Federation_logo.svg/120px-International_Coaching_Federation_logo.svg.png',
  'APA': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/American_Psychological_Association_logo.svg/120px-American_Psychological_Association_logo.svg.png',
  'AIA': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/American_Institute_of_Architects_logo.svg/120px-American_Institute_of_Architects_logo.svg.png',
  'ASCE': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/ASCE_logo.svg/120px-ASCE_logo.svg.png',
  'ASME': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/ASME_logo.svg/120px-ASME_logo.svg.png',
  'IEEE': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/IEEE_logo.svg/120px-IEEE_logo.svg.png',
  'AIChE': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/AIChE_logo.svg/120px-AIChE_logo.svg.png',
  'BMES': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/BMES_logo.svg/120px-BMES_logo.svg.png',
  'AIAA': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/AIAA_logo.svg/120px-AIAA_logo.svg.png',
  'Nike': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Logo_NIKE.svg/120px-Logo_NIKE.svg.png',
  'IMG Academy': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/IMG_Academy_logo.svg/120px-IMG_Academy_logo.svg.png',
  'Under Armour': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Under_armour_logo.svg/120px-Under_armour_logo.svg.png',
  'ESPN': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/ESPN_wordmark.svg/120px-ESPN_wordmark.svg.png',
  'NEC': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/New_England_Conservatory_seal.svg/120px-New_England_Conservatory_seal.svg.png',
  'Yamaha': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Yamaha_Motor_Logo.svg/120px-Yamaha_Motor_Logo.svg.png',
  'Bands of America': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Bands_of_America_logo.svg/120px-Bands_of_America_logo.svg.png',
  'Summer Science Program': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/MIT_logo.svg/120px-MIT_logo.svg.png',
  'Clark Scholar': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/MIT_logo.svg/120px-MIT_logo.svg.png',
  'Simons Summer Research': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Stony_Brook_Athletics_logo.svg/120px-Stony_Brook_Athletics_logo.svg.png',
  'YYGS': 'logos/yale.png',
  'YYGS Science': 'logos/yale.png',
  'YYGS Politics': 'logos/yale.png',
  'YYGS Business': 'logos/yale.png',
  'Triton AI Camp': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/UCSD_Athletics_logo.svg/120px-UCSD_Athletics_logo.svg.png',
  'SUMaC': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Signature_of_Stanford_University.svg/200px-Signature_of_Stanford_University.svg.png',
  'Stanford AI4ALL': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Signature_of_Stanford_University.svg/200px-Signature_of_Stanford_University.svg.png',
  'Medill Journalism': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Northwestern_University_seal.svg/120px-Northwestern_University_seal.svg.png',
  'PROMYS': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Boston_University_seal.svg/120px-Boston_University_seal.svg.png',
  'Ross Math': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/MIT_logo.svg/120px-MIT_logo.svg.png',
  'WPI': 'logos/WPI.webp',
  'BU': 'logos/BU.png',
  'Northeastern': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Boston_University_seal.svg/120px-Boston_University_seal.svg.png',
  'Yale Writers': 'logos/yale.png',
  'Yale Summer Session': 'logos/yale.png',
  'Yale Model UN': 'logos/yale.png',
  'Yale Global Scholars': 'logos/yale.png',
  'Smith Summer Science': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Smith_College_seal.svg/120px-Smith_College_seal.svg.png',
  'Garcia MURI': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Stony_Brook_Athletics_logo.svg/120px-Stony_Brook_Athletics_logo.svg.png',
  'Junior Statesmen': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Junior_Statesmen_of_America_logo.svg/120px-Junior_Statesmen_of_America_logo.svg.png',
  'JSA': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Junior_Statesmen_of_America_logo.svg/120px-Junior_Statesmen_of_America_logo.svg.png',
  'Harvard Summer': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Harvard_University_coat_of_arms.svg/120px-Harvard_University_coat_of_arms.svg.png',
  'Stanford Pre-College': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Signature_of_Stanford_University.svg/200px-Signature_of_Stanford_University.svg.png',
  'MIT LaunchX': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/MIT_logo.svg/120px-MIT_logo.svg.png',
  'MIT RSI': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/MIT_logo.svg/120px-MIT_logo.svg.png',
};

// Get logo for a provider
function getProviderLogo(provider) {
  return collegeLogos[provider] || null;
}
