// College logos mapping
const collegeLogos = {
  'MIT': 'logos/MIT.png',
  'Stanford': 'logos/Stanford.png',
  'Harvard': 'logos/harvard.png',
  'Yale': 'logos/yale.png',
  'Columbia': 'logos/Columbia.png',
  'Brown': 'logos/brown.jpg',
  'Duke': 'logos/duke.png',
  'Princeton': 'logos/Princeton.png',
  'Cornell': 'logos/Cornell.png',
  'UPenn': 'logos/Penn.png',
  'UPenn Wharton': 'logos/Penn.png',
  'Berklee': 'logos/Berklee.png',
  'Berklee Online': 'logos/Berklee.png',
  'Berklee College': 'logos/Berklee.png',
  'RISD': 'logos/RISD.png',
  'Juilliard': 'logos/Juilliard.png',
  'Khan Academy': 'logos/khan.png',
  'Google': 'logos/google.webp',
  'Coursera': 'logos/Coursera.png',
  'Wharton': 'logos/Penn.png',
  'Parsons': 'logos/Parsons.png',
  'Apple': 'logos/apple.webp',
  'Girls Who Code': 'logos/Girls_Who_Code.png',
  'Y Combinator': 'logos/Y combinator.webp',
  'Babson': 'logos/babson.png',
  'Northwestern': 'logos/Northwestern.png',
  'Kenyon': 'logos/Kenyon.png',
  'Iowa Writers': 'logos/Iowa.png',
  'U of Iowa': 'logos/Iowa.png',
  'edX': 'logos/edX.png',
  'MIT OCW': 'logos/MIT.png',
  'UC Berkeley': 'logos/UC Berkeley.png',
  'Berkeley Haas': 'logos/UC Berkeley.png',
  'UCLA': 'logos/UCLA.png',
  'NYU': 'logos/NYU.png',
  'NYU Tisch': 'logos/NYU.png',
  'NYU Gallatin': 'logos/NYU.png',
  'Carnegie Mellon': 'logos/Carnegie Mellon.png',
  'CMU': 'logos/Carnegie Mellon.png',
  'CMU S3': 'logos/Carnegie Mellon.png',
  'Georgetown': 'logos/Georgetown.png',
  'Georgetown Prep': 'logos/Georgetown.png',
  'Ross Program': 'logos/MIT.png',
  'Boston University': 'logos/BU.png',
  'Telluride Association': 'logos/MIT.png',
  'NASA': 'logos/Nasa.png',
  'NASA JSC': 'logos/Nasa.png',
  'Smith College': 'logos/smith.png',
  'Stony Brook': 'logos/stony brook.png',
  'UC San Diego': 'logos/UC San diego.png',
  'UCSD': 'logos/UC San diego.png',
  'Smithsonian': 'logos/smithsonian.png',
  'AMNH': 'logos/AMNH.png',
  'Johns Hopkins': 'logos/JHU.png',
  'JHU': 'logos/JHU.png',
  'Duke TIP': 'logos/duke.png',
  'Oxford': 'logos/Oxford.png',
  'Cambridge': 'logos/Cambridge.png',
  'LSE': 'logos/LSE.png',
  'Imperial': 'logos/Imperial.png',
  'ETH Zurich': 'logos/ETHZurich.png',
  'UTokyo': 'logos/UTokyo.png',
  'NUS': 'logos/NUS.png',
  'HKU': 'logos/HKU.png',
  'U of T': 'logos/U of T.png',
  'McGill': 'logos/Mcgill.png',
  'UBC': 'logos/UBC.png',
  'Waterloo': 'logos/Waterloo.png',
  'Microsoft': 'logos/microsoft.png',
  'Meta': 'logos/meta.png',
  'NVIDIA': 'logos/Nvidia.png',
  'SpaceX': 'logos/spaceX.png',
  'Blue Origin': 'logos/BlueOrigin.png',
  'Stripe': 'logos/Stripe.png',
  'Airbnb': 'logos/Airbnb.png',
  'Uber': 'logos/Uber.png',
  'Twitter/X': 'logos/Twitter.png',
  'Amazon': 'logos/amazon.png',
  'Netflix': 'logos/Netflix.png',
  'Spotify': 'logos/spotify.png',
  'Notion': 'logos/Notion.png',
  'Figma': 'logos/Figma.png',
  'JPL': 'logos/JPL.png',
  'Fermilab': 'logos/Fermilab.png',
  'CERN': 'logos/CERN.png',
  'Peace Corps': 'logos/PeaceCorps.png',
  'Teach For America': 'logos/TFA.png',
  'TFA': 'logos/TFA.png',
  'City Year': 'logos/CityYear.png',
  'Global Health Corps': 'logos/GHC.png',
  'GHC': 'logos/GHC.png',
  'West Point': 'logos/west point.png',
  'Air Force Academy': 'logos/USAFA.png',
  'USAFA': 'logos/USAFA.png',
  'DECA': 'logos/DECA.png',
  'Science Olympiad': 'logos/ScienceOlympiad.png',
  'Mathcamp': 'logos/MIT.png',
  'HCSSiM': 'logos/hampshire.png',
  'Hampshire College': 'logos/hampshire.png',
  'CalArts': 'logos/Calarts.png',
  'Pratt': 'logos/pratt.webp',
  'Kellogg': 'logos/Kellogg.png',
  'Haas': 'logos/Haas.png',
  'Michigan Ross': 'logos/MichiganRoss.png',
  'Tuck': 'logos/Dartmouth.png',
  'Darden': 'logos/Darden.png',
  'Yale Law': 'logos/yale.png',
  'Columbia Business': 'logos/Columbia.png',
  'USC': 'logos/USC.png',
  'UC Davis': 'logos/UC davis.png',
  'UCI': 'logos/UC irvine.png',
  'UC Santa Barbara': 'logos/UCSB.png',
  'UCSB': 'logos/UCSB.png',
  'Arizona State': 'logos/ASU.png',
  'ASU': 'logos/ASU.png',
  'University of Colorado': 'logos/University of colorado.png',
  'CU Boulder': 'logos/University of colorado.png',
  'University of Miami': 'logos/university of miami.png',
  'Miami': 'logos/university of miami.png',
  'University of Denver': 'logos/Denver.png',
  'Denver': 'logos/Denver.png',
  'University of Hawaii': 'logos/University of Hawaii.png',
  'UH Manoa': 'logos/University of Hawaii.png',
  'University of Florida': 'logos/University of florida.png',
  'UF': 'logos/University of florida.png',
  'Penn State': 'logos/Penn.png',
  'Ohio State': 'logos/Ohio state.png',
  'University of Michigan': 'logos/University of michigan.png',
  'UMich': 'logos/University of michigan.png',
  'Georgia Tech': 'logos/Georgia tech.png',
  'Virginia Tech': 'logos/Virginia tech.png',
  'University of Texas': 'logos/UTAustin.png',
  'WashU': 'logos/washu.png',
  'Rice': 'logos/Rice.png',
  'Dartmouth': 'logos/Dartmouth.png',
  'Dartmouth Tuck': 'logos/Dartmouth.png',
  'Williams': 'logos/Williams.png',
  'Amherst': 'logos/amherst.png',
  'Swarthmore': 'logos/swarthmore.png',
  'Middlebury': 'logos/Middlebury.png',
  'Carleton': 'logos/carleton.png',
  'Oberlin': 'logos/Oberlin.png',
  'Vassar': 'logos/vassar.png',
  'Wellesley': 'logos/wellesley.png',
  'Barnard': 'logos/Barnard.png',
  'Bryn Mawr': 'logos/bryn mawr.png',
  'Interlochen': 'logos/interlochen.png',
  'SAIC': 'logos/SAIC.png',
  'Cooper Union': 'logos/CooperUnion.png',
  'SCAD': 'logos/SCAD.png',
  'Ringling': 'logos/Ringling.png',
  'Full Sail': 'logos/FullSail.png',
  'General Assembly': 'logos/GeneralAssembly.png',
  'Google UX': 'logos/google.webp',
  'AMA': 'logos/AMA.png',
  'Hootsuite': 'logos/Hootsuite.png',
  'Moz': 'logos/Moz.png',
  'Fast.ai': 'logos/FastAI.png',
  '(ISC)2': 'logos/ISC2.png',
  'AWS': 'logos/AWS.png',
  'PMI': 'logos/PMI.png',
  'SHRM': 'logos/SHRM.png',
  'ICF': 'logos/ICF.png',
  'APA': 'logos/APA.png',
  'AIA': 'logos/AIA.png',
  'ASCE': 'logos/ASCE.png',
  'ASME': 'logos/ASME.png',
  'IEEE': 'logos/IEEE.png',
  'AIChE': 'logos/AIChE.png',
  'BMES': 'logos/BMES.png',
  'AIAA': 'logos/AIAA.png',
  'Nike': 'logos/Nike.png',
  'IMG Academy': 'logos/IMG.png',
  'Under Armour': 'logos/UnderArmour.png',
  'ESPN': 'logos/ESPN.png',
  'NEC': 'logos/NEC.jpg',
  'Yamaha': 'logos/Yamaha.png',
  'Bands of America': 'logos/USSC.png',
  'Summer Science Program': 'logos/MIT.png',
  'Clark Scholar': 'logos/MIT.png',
  'Simons Summer Research': 'logos/stony brook.png',
  'YYGS': 'logos/yale.png',
  'YYGS Science': 'logos/yale.png',
  'YYGS Politics': 'logos/yale.png',
  'YYGS Business': 'logos/yale.png',
  'Triton AI Camp': 'logos/UC San diego.png',
  'SUMaC': 'logos/Stanford.png',
  'Stanford AI4ALL': 'logos/Stanford.png',
  'Medill Journalism': 'logos/Northwestern.png',
  'PROMYS': 'logos/BU.png',
  'Ross Math': 'logos/MIT.png',
  'WPI': 'logos/WPI.webp',
  'BU': 'logos/BU.png',
  'Northeastern': 'logos/Northeastern.png',
  'Yale Writers': 'logos/yale.png',
  'Yale Summer Session': 'logos/yale.png',
  'Yale Model UN': 'logos/yale.png',
  'Yale Global Scholars': 'logos/yale.png',
  'Smith Summer Science': 'logos/smith.png',
  'Garcia MURI': 'logos/stony brook.png',
  'Junior Statesmen': 'logos/JSA.jpg',
  'JSA': 'logos/JSA.jpg',
  'Harvard Summer': 'logos/harvard.png',
  'Stanford Pre-College': 'logos/Stanford.png',
  'MIT LaunchX': 'logos/MIT.png',
  'MIT RSI': 'logos/MIT.png',
  'FIT': 'logos/FIT.png',
  'SVA': 'logos/SVA.png',
  'Academy of Art': 'logos/Academy of art.png',
  'Davidson': 'logos/Davidson.jpg',
  'UVA': 'logos/UVA.png',
  'UVA Darden': 'logos/UVA.png',
};

// Get logo for a provider
function getProviderLogo(provider) {
  return collegeLogos[provider] || null;
}
