// Sunnyday V2 - Programs Database

const categories = [
  { id: 'summer', name: 'Summer Programs', icon: '🌱', color: '#6BCB77' },
  { id: 'stem', name: 'STEM', icon: '🔬', color: '#6BCBFF' },
  { id: 'coding', name: 'Coding', icon: '💻', color: '#6BCBFF' },
  { id: 'business', name: 'Business', icon: '💼', color: '#FFD93D' },
  { id: 'writing', name: 'Writing', icon: '✍️', color: '#FF8FA3' },
  { id: 'arts', name: 'Arts', icon: '🎨', color: '#FF6B35' },
  { id: 'free', name: 'Free Programs', icon: '🎁', color: '#6BCB77' },
  { id: 'research', name: 'Research', icon: '🔍', color: '#9B59B6' },
  { id: 'sports', name: 'Sports', icon: '⚽', color: '#27AE60' },
  { id: 'music', name: 'Music', icon: '🎵', color: '#E74C3C' },
];

const programs = [
  { id: 1, title: 'MIT LaunchX', provider: 'MIT', category: 'summer', tags: ['Entrepreneurship'], description: 'Build startups.', cost: '$2,500+', website: 'https://launchx.com' },
  { id: 2, title: 'MIT RSI', provider: 'MIT', category: 'research', tags: ['Research', 'Free'], description: 'Premier research.', cost: 'Free', website: 'https://www.esp.org' },
  { id: 3, title: 'Stanford Pre-College', provider: 'Stanford', category: 'summer', tags: ['Prestigious'], description: 'Experience Stanford.', cost: '$1,000+', website: 'https://precollege.stanford.edu' },
  { id: 4, title: 'Harvard Summer', provider: 'Harvard', category: 'summer', tags: ['Prestigious'], description: 'Harvard courses.', cost: '$2,900+', website: 'https://summer.schools.harvard.edu' },
  { id: 5, title: 'Yale Writers', provider: 'Yale', category: 'writing', tags: ['Writing'], description: 'Writing workshop.', cost: '$2,000', website: 'https://english.yale.edu' },
  { id: 6, title: 'Khan Academy', provider: 'Khan Academy', category: 'coding', tags: ['Free', 'Online'], description: 'Learn coding.', cost: 'Free', website: 'https://khanacademy.org' },
  { id: 7, title: 'Google Code Next', provider: 'Google', category: 'coding', tags: ['Free', 'CS'], description: 'Free CS education.', cost: 'Free', website: 'https://codenext.withgoogle.com' },
  { id: 8, title: 'Coursera', provider: 'Coursera', category: 'free', tags: ['Free', 'Online'], description: 'Free courses.', cost: 'Free', website: 'https://coursera.org' },
  { id: 9, title: 'Wharton Summer', provider: 'UPenn', category: 'business', tags: ['Business', 'Finance'], description: 'Business program.', cost: '$4,000+', website: 'https://wharton.upenn.edu' },
  { id: 10, title: 'RISD Pre-College', provider: 'RISD', category: 'arts', tags: ['Art', 'Design'], description: 'Build portfolio.', cost: '$3,000+', website: 'https://risd.edu' },
  { id: 11, title: 'Stanford AI4ALL', provider: 'Stanford', category: 'stem', tags: ['AI', 'Machine Learning'], description: 'Intro to AI.', cost: 'Free', website: 'https://ai4all.stanford.edu' },
  { id: 12, title: 'Yale Summer Session', provider: 'Yale', category: 'summer', tags: ['College Credit'], description: 'Yale courses.', cost: '$3,000+', website: 'https://summer.yale.edu' },
  { id: 13, title: 'Columbia Summer', provider: 'Columbia', category: 'summer', tags: ['NYC', 'Prestigious'], description: 'Columbia in NYC.', cost: '$2,500+', website: 'https://summer.columbia.edu' },
  { id: 14, title: 'Brown Pre-College', provider: 'Brown', category: 'summer', tags: ['Liberal Arts'], description: 'Explore interests.', cost: '$2,000+', website: 'https://precollege.brown.edu' },
  { id: 15, title: 'Duke Summer', provider: 'Duke', category: 'summer', tags: ['Research'], description: 'Duke experience.', cost: '$2,500+', website: 'https://summer.duke.edu' },
  { id: 16, title: 'Ross Math', provider: 'Ross Program', category: 'stem', tags: ['Math', 'Residential'], description: 'Mathematics deep dive.', cost: 'Free', website: 'https://rossprogram.org' },
  { id: 17, title: 'PROMYS', provider: 'Boston University', category: 'stem', tags: ['Math', 'Number Theory'], description: 'Math for Scientists.', cost: '$2,000+', website: 'https://promys.org' },
  { id: 18, title: 'SUMaC', provider: 'Stanford', category: 'stem', tags: ['Math', 'Prestigious'], description: 'Stanford Math Camp.', cost: '$3,000+', website: 'https://sumac.stanford.edu' },
  { id: 19, title: 'Telluride Association', provider: 'Telluride', category: 'summer', tags: ['Liberal Arts', 'Full Ride'], description: 'Free programs.', cost: 'Free', website: 'https://tellurideassociation.org' },
  { id: 20, title: 'Juilliard Pre-College', provider: 'Juilliard', category: 'arts', tags: ['Music', 'Performance'], description: 'Conservatory training.', cost: '$4,000+', website: 'https://juilliard.edu' },
  { id: 21, title: 'Parsons Summer', provider: 'Parsons', category: 'arts', tags: ['Fashion', 'Design'], description: 'Design at Parsons.', cost: '$3,000+', website: 'https://parsons.edu' },
  { id: 22, title: 'Apple Swift Camp', provider: 'Apple', category: 'coding', tags: ['iOS', 'Mobile'], description: 'Build iOS apps.', cost: 'Free', website: 'https://developer.apple.com' },
  { id: 23, title: 'Girls Who Code', provider: 'Girls Who Code', category: 'coding', tags: ['Free', 'Girls'], description: 'Coding for girls.', cost: 'Free', website: 'https://girlswhocode.com' },
  { id: 24, title: 'Y Combinator', provider: 'Y Combinator', category: 'business', tags: ['Startup', 'Tech'], description: 'Startup world.', cost: 'Free', website: 'https://ycombinator.com' },
  { id: 25, title: 'Babson Summer', provider: 'Babson', category: 'business', tags: ['Entrepreneurship'], description: 'Venture building.', cost: '$3,000+', website: 'https://babson.edu' },
  { id: 26, title: 'Medill Journalism', provider: 'Northwestern', category: 'writing', tags: ['Journalism', 'Media'], description: 'Journalism at NU.', cost: '$3,000+', website: 'https://medill.northwestern.edu' },
  { id: 27, title: 'Kenyon Writing', provider: 'Kenyon', category: 'writing', tags: ['Writing', 'Literature'], description: 'Intensive writing.', cost: '$2,500+', website: 'https://kenyon.edu' },
  { id: 28, title: 'Iowa Writers', provider: 'U of Iowa', category: 'writing', tags: ['Writing', 'Residential'], description: 'Writing workshop.', cost: '$2,500', website: 'https://writersworkshop.uiowa.edu' },
  { id: 29, title: 'edX', provider: 'edX', category: 'free', tags: ['Free', 'Online'], description: 'Free Harvard/MIT.', cost: 'Free', website: 'https://edx.org' },
  { id: 30, title: 'MIT OCW', provider: 'MIT', category: 'free', tags: ['Free', 'Online'], description: 'Free MIT materials.', cost: 'Free', website: 'https://ocw.mit.edu' },
  { id: 31, title: 'UC Berkeley Summer', provider: 'UC Berkeley', category: 'summer', tags: ['Bay Area', 'STEM'], description: 'Summer at Berkeley.', cost: '$1,500+', website: 'https://summer.berkeley.edu' },
  { id: 32, title: 'UCLA Summer', provider: 'UCLA', category: 'summer', tags: ['LA', 'College Credit'], description: 'Summer at UCLA.', cost: '$1,500+', website: 'https://summer.ucla.edu' },
  { id: 33, title: 'NYU Gallatin', provider: 'NYU', category: 'summer', tags: ['NYC', 'Interdisciplinary'], description: 'Gallatin program.', cost: '$3,000+', website: 'https://gallatin.nyu.edu' },
  { id: 34, title: 'Carnegie Mellon', provider: 'CMU', category: 'stem', tags: ['Robotics', 'STEM'], description: 'Explore CMU.', cost: '$2,000+', website: 'https://cmu.edu' },
  { id: 35, title: 'Georgetown Summer', provider: 'Georgetown', category: 'summer', tags: ['IR', 'Politics'], description: 'Explore Georgetown.', cost: '$3,000+', website: 'https://georgetown.edu' },
  { id: 36, title: 'UPenn Summer', provider: 'UPenn', category: 'summer', tags: ['Business', 'Engineering'], description: 'UPenn programs.', cost: '$2,000+', website: 'https://summer.sas.upenn.edu' },
  { id: 37, title: 'Cornell Summer', provider: 'Cornell', category: 'summer', tags: ['Prestigious', 'Research'], description: 'Cornell experience.', cost: '$3,000+', website: 'https://sce.cornell.edu' },
  { id: 38, title: 'Princeton Summer', provider: 'Princeton', category: 'summer', tags: ['Research', 'STEM'], description: 'Princeton research.', cost: '$3,000+', website: 'https://www.princeton.edu' },
  { id: 39, title: 'WPI', provider: 'WPI', category: 'stem', tags: ['Engineering', 'Robotics'], description: 'Engineering at WPI.', cost: '$2,000+', website: 'https://wpi.edu' },
  { id: 40, title: 'BU Summer', provider: 'BU', category: 'summer', tags: ['Research', 'Pre-Med'], description: 'Summer at BU.', cost: '$2,000+', website: 'https://bu.edu' },
  { id: 41, title: 'Northeastern', provider: 'Northeastern', category: 'stem', tags: ['Co-op', 'Engineering'], description: 'Northeastern programs.', cost: '$2,000+', website: 'https://northeastern.edu' },
  { id: 42, title: 'NYU Tisch', provider: 'NYU Tisch', category: 'arts', tags: ['Film', 'Drama'], description: 'Film and drama.', cost: '$3,000+', website: 'https://tisch.nyu.edu' },
  { id: 43, title: 'USC Film', provider: 'USC', category: 'arts', tags: ['Film', 'Hollywood'], description: 'Film production.', cost: '$3,000+', website: 'https://cinema.usc.edu' },
  { id: 44, title: 'FIT Summer', provider: 'FIT', category: 'arts', tags: ['Fashion', 'Design'], description: 'Fashion at FIT.', cost: '$2,000+', website: 'https://fitnyc.edu' },
  { id: 45, title: 'SVA', provider: 'SVA', category: 'arts', tags: ['Animation', 'Film'], description: 'Animation at SVA.', cost: '$2,500+', website: 'https://sva.edu' },
  { id: 46, title: 'Berklee', provider: 'Berklee', category: 'arts', tags: ['Music', 'Performance'], description: 'Music at Berklee.', cost: '$500+', website: 'https://berklee.edu' },
  { id: 47, title: 'YYGS Science', provider: 'Yale', category: 'stem', tags: ['Research', 'Science'], description: 'Yale Global Scholars.', cost: '$3,000+', website: 'https://globalscholars.yale.edu' },
  { id: 48, title: 'YYGS Politics', provider: 'Yale', category: 'business', tags: ['Politics', 'International'], description: 'Yale politics.', cost: '$3,000+', website: 'https://globalscholars.yale.edu' },
  { id: 49, title: 'YYGS Business', provider: 'Yale', category: 'business', tags: ['Business', 'Leadership'], description: 'Yale business.', cost: '$3,000+', website: 'https://globalscholars.yale.edu' },
  { id: 50, title: 'NASA Space Camp', provider: 'NASA', category: 'stem', tags: ['Space', 'Engineering'], description: 'Space exploration.', cost: '$1,000+', website: 'https://spacecamp.com' },
  { id: 51, title: 'Smith Summer Science', provider: 'Smith College', category: 'stem', tags: ['STEM', 'Girls'], description: 'Science for girls.', cost: '$2,500+', website: 'https://smith.edu' },
  { id: 52, title: 'Garcia MURI', provider: 'Stony Brook', category: 'research', tags: ['STEM', 'Research'], description: 'Materials research.', cost: 'Free', website: 'https://garciasummerprogram.com' },
  { id: 53, title: 'Triton AI Camp', provider: 'UC San Diego', category: 'coding', tags: ['AI', 'Machine Learning'], description: 'AI for high schoolers.', cost: '$500+', website: 'https://aicamp.ucsd.edu' },
  { id: 54, title: 'Smithsonian', provider: 'Smithsonian', category: 'research', tags: ['Research', 'Museum'], description: 'Smithsonian programs.', cost: '$1,500+', website: 'https://smithsonian.edu' },
  { id: 55, title: 'AMNH', provider: 'AMNH', category: 'research', tags: ['Science', 'Museum'], description: 'AMNH programs.', cost: '$1,500+', website: 'https://amnh.org' },
  { id: 56, title: 'Johns Hopkins CTY', provider: 'JHU', category: 'stem', tags: ['Gifted', 'Academic'], description: 'Talented Youth.', cost: '$1,500+', website: 'https://cty.jhu.edu' },
  { id: 57, title: 'Duke TIP', provider: 'Duke', category: 'stem', tags: ['Gifted', 'Academic'], description: 'Talent ID.', cost: '$1,500+', website: 'https://tip.duke.edu' },
  { id: 58, title: 'Oxford', provider: 'Oxford', category: 'summer', tags: ['UK', 'Residential'], description: 'Oxford summer.', cost: '$4,000+', website: 'https://ox.ac.uk' },
  { id: 59, title: 'Cambridge', provider: 'Cambridge', category: 'summer', tags: ['UK', 'Residential'], description: 'Cambridge summer.', cost: '$4,000+', website: 'https://cam.ac.uk' },
  { id: 60, title: 'LSE', provider: 'LSE', category: 'business', tags: ['Business', 'Economics'], description: 'LSE programs.', cost: '$4,000+', website: 'https://lse.ac.uk' },
  { id: 61, title: 'Imperial', provider: 'Imperial', category: 'stem', tags: ['Engineering', 'Science'], description: 'Imperial programs.', cost: '$4,000+', website: 'https://imperial.ac.uk' },
  { id: 62, title: 'ETH Zurich', provider: 'ETH', category: 'stem', tags: ['Engineering', 'Research'], description: 'ETH Zurich.', cost: '$3,000+', website: 'https://ethz.ch' },
  { id: 63, title: 'UTokyo', provider: 'UTokyo', category: 'summer', tags: ['Japan', 'Asia'], description: 'Tokyo summer.', cost: '$2,500+', website: 'https://u-tokyo.ac.jp' },
  { id: 64, title: 'NUS', provider: 'NUS', category: 'summer', tags: ['Asia', 'Singapore'], description: 'NUS programs.', cost: '$2,000+', website: 'https://nus.edu.sg' },
  { id: 65, title: 'HKU', provider: 'HKU', category: 'summer', tags: ['Asia', 'Hong Kong'], description: 'HKU programs.', cost: '$2,000+', website: 'https://hku.hk' },
  { id: 66, title: 'U of T', provider: 'U of T', category: 'research', tags: ['Canada', 'Research'], description: 'Toronto programs.', cost: '$2,000+', website: 'https://utoronto.ca' },
  { id: 67, title: 'McGill', provider: 'McGill', category: 'summer', tags: ['Canada', 'Research'], description: 'McGill programs.', cost: '$2,500+', website: 'https://mcgill.ca' },
  { id: 68, title: 'UBC', provider: 'UBC', category: 'stem', tags: ['Canada', 'Science'], description: 'UBC programs.', cost: '$2,500+', website: 'https://ubc.ca' },
  { id: 69, title: 'Waterloo', provider: 'Waterloo', category: 'stem', tags: ['Canada', 'Math'], description: 'Waterloo math.', cost: '$2,000+', website: 'https://uwaterloo.ca' },
  { id: 70, title: 'Microsoft Explore', provider: 'Microsoft', category: 'coding', tags: ['Software', 'Internship'], description: 'Microsoft Explore.', cost: 'Paid', website: 'https://careers.microsoft.com' },
  { id: 71, title: 'Google Summer', provider: 'Google', category: 'coding', tags: ['Tech', 'Internship'], description: 'Google programs.', cost: 'Paid', website: 'https://careers.google.com' },
  { id: 72, title: 'Meta Summer', provider: 'Meta', category: 'coding', tags: ['Tech', 'VR/AR'], description: 'Meta programs.', cost: 'Paid', website: 'https://metacareers.com' },
  { id: 73, title: 'Apple Summer', provider: 'Apple', category: 'stem', tags: ['Tech', 'Hardware'], description: 'Apple programs.', cost: 'Paid', website: 'https://apple.com/careers' },
  { id: 74, title: 'NVIDIA', provider: 'NVIDIA', category: 'coding', tags: ['AI', 'GPU'], description: 'NVIDIA programs.', cost: 'Paid', website: 'https://nvidia.com/careers' },
  { id: 75, title: 'SpaceX', provider: 'SpaceX', category: 'stem', tags: ['Space', 'Rocketry'], description: 'SpaceX programs.', cost: 'Unpaid', website: 'https://spacex.com/careers' },
  { id: 76, title: 'Blue Origin', provider: 'Blue Origin', category: 'stem', tags: ['Space', 'Aviation'], description: 'Blue Origin.', cost: 'Unpaid', website: 'https://blueorigin.com' },
  { id: 77, title: 'Stripe', provider: 'Stripe', category: 'coding', tags: ['FinTech', 'Engineering'], description: 'Stripe programs.', cost: 'Paid', website: 'https://stripe.com/jobs' },
  { id: 78, title: 'Airbnb', provider: 'Airbnb', category: 'business', tags: ['Tech', 'Hospitality'], description: 'Airbnb programs.', cost: 'Paid', website: 'https://airbnb.com/careers' },
  { id: 79, title: 'Uber', provider: 'Uber', category: 'stem', tags: ['Tech', 'Transportation'], description: 'Uber programs.', cost: 'Paid', website: 'https://uber.com/careers' },
  { id: 80, title: 'Twitter/X', provider: 'Twitter/X', category: 'coding', tags: ['Tech', 'Social Media'], description: 'Twitter programs.', cost: 'Paid', website: 'https://careers.twitter.com' },
  { id: 81, title: 'Amazon', provider: 'Amazon', category: 'stem', tags: ['Tech', 'Logistics'], description: 'Amazon programs.', cost: 'Paid', website: 'https://amazon.jobs' },
  { id: 82, title: 'Netflix', provider: 'Netflix', category: 'arts', tags: ['Entertainment', 'Tech'], description: 'Netflix programs.', cost: 'Paid', website: 'https://netflixcareers.com' },
  { id: 83, title: 'Spotify', provider: 'Spotify', category: 'arts', tags: ['Music', 'Tech'], description: 'Spotify programs.', cost: 'Paid', website: 'https://spotifyjobs.com' },
  { id: 84, title: 'Notion', provider: 'Notion', category: 'coding', tags: ['Productivity', 'Tech'], description: 'Notion programs.', cost: 'Paid', website: 'https://notion.so/careers' },
  { id: 85, title: 'Figma', provider: 'Figma', category: 'arts', tags: ['Design', 'Tech'], description: 'Figma programs.', cost: 'Paid', website: 'https://figma.com/careers' },
  { id: 86, title: 'NASA JSC', provider: 'NASA', category: 'stem', tags: ['Space', 'Engineering'], description: 'NASA JSC.', cost: '$1,000+', website: 'https://nasajobs.nasa.gov' },
  { id: 87, title: 'JPL', provider: 'JPL', category: 'stem', tags: ['Space', 'Robotics'], description: 'JPL programs.', cost: 'Free', website: 'https://jpl.nasa.gov' },
  { id: 88, title: 'Fermilab', provider: 'Fermilab', category: 'research', tags: ['Physics', 'Research'], description: 'Fermilab programs.', cost: 'Free', website: 'https://fnal.gov' },
  { id: 89, title: 'CERN', provider: 'CERN', category: 'stem', tags: ['Physics', 'Science'], description: 'CERN programs.', cost: '$2,000+', website: 'https://careers.cern.ch' },
  { id: 90, title: 'Peace Corps', provider: 'Peace Corps', category: 'free', tags: ['Service', 'Global'], description: 'Global service.', cost: 'Free', website: 'https://peacecorps.gov' },
  { id: 91, title: 'Teach For America', provider: 'TFA', category: 'free', tags: ['Education', 'Teaching'], description: 'Summer institute.', cost: 'Free', website: 'https://teachforamerica.org' },
  { id: 92, title: 'City Year', provider: 'City Year', category: 'free', tags: ['Education', 'Urban'], description: 'City Year.', cost: 'Free', website: 'https://cityyear.org' },
  { id: 93, title: 'Global Health Corps', provider: 'GHC', category: 'free', tags: ['Health', 'Global'], description: 'Global Health.', cost: 'Free', website: 'https://ghcorps.org' },
  { id: 94, title: 'West Point', provider: 'West Point', category: 'business', tags: ['Leadership', 'Military'], description: 'West Point.', cost: 'Free', website: 'https://westpoint.edu' },
  { id: 95, title: 'Air Force Academy', provider: 'USAFA', category: 'business', tags: ['Leadership', 'Aerospace'], description: 'Air Force Academy.', cost: 'Free', website: 'https://usafa.edu' },
  { id: 96, title: 'Parliamentary Debate', provider: 'Harvard', category: 'writing', tags: ['Debate', 'Model UN'], description: 'Harvard debate.', cost: '$2,500+', website: 'https://harvard.edu' },
  { id: 97, title: 'Yale Model UN', provider: 'Yale', category: 'business', tags: ['Model UN', 'Diplomacy'], description: 'Yale Model UN.', cost: '$2,000+', website: 'https://yale.edu' },
  { id: 98, title: 'Georgetown Model UN', provider: 'Georgetown', category: 'business', tags: ['Model UN', 'International'], description: 'GU Model UN.', cost: '$1,500+', website: 'https://georgetown.edu' },
  { id: 99, title: 'Junior Statesmen', provider: 'JSA', category: 'business', tags: ['Debate', 'Politics'], description: 'Junior Statesmen.', cost: '$2,000+', website: 'https://jsa.org' },
  { id: 100, title: 'Stanford Athletics', provider: 'Stanford', category: 'stem', tags: ['Athletics', 'Sports'], description: 'Stanford sports.', cost: '$1,000+', website: 'https://stanford.edu' },
  { id: 101, title: 'USC Athletics', provider: 'USC', category: 'stem', tags: ['Sports', 'Football'], description: 'USC sports.', cost: '$1,000+', website: 'https://usc.edu' },
  { id: 102, title: 'MedSTEM', provider: 'Johns Hopkins', category: 'stem', tags: ['Medicine', 'Research'], description: 'Explore medicine.', cost: '$1,500', website: 'https://jhu.edu' },
  { id: 103, title: 'DECA', provider: 'DECA', category: 'business', tags: ['Business', 'Competition'], description: 'Business competitions.', cost: '$150+', website: 'https://deca.org' },
  { id: 104, title: 'Science Olympiad', provider: 'Science Olympiad', category: 'stem', tags: ['STEM', 'Team'], description: 'Science competitions.', cost: '$50+', website: 'https://scioly.org' },
  { id: 105, title: 'Mathcamp', provider: 'Mathcamp', category: 'stem', tags: ['Math', 'Residential'], description: 'Joy of mathematics.', cost: '$500+', website: 'https://mathcamp.org' },
  { id: 106, title: 'HCSSiM', provider: 'Hampshire College', category: 'stem', tags: ['Math', 'Creative'], description: 'Math at Hampshire.', cost: '$2,000+', website: 'https://hcssim.org' },
  { id: 107, title: 'CalArts', provider: 'CalArts', category: 'arts', tags: ['Animation', 'Film'], description: 'Arts at CalArts.', cost: '$2,000+', website: 'https://calarts.edu' },
  { id: 108, title: 'Pratt', provider: 'Pratt', category: 'arts', tags: ['Art', 'Design'], description: 'Creative arts.', cost: '$2,500+', website: 'https://pratt.edu' },
  { id: 109, title: 'OBP Summer', provider: 'OBP', category: 'business', tags: ['Business', 'Entrepreneurship'], description: 'Summer business program.', cost: '$2,500+', website: 'https://objectivebrief.com' },
  { id: 110, title: 'Wharton LBW', provider: 'UPenn Wharton', category: 'business', tags: ['Business', 'Leadership'], description: 'Leadership in Business.', cost: '$4,000+', website: 'https://wharton.upenn.edu' },
  { id: 111, title: 'Kellogg Summer', provider: 'Northwestern', category: 'business', tags: ['Business', 'Management'], description: 'Business at Kellogg.', cost: '$3,000+', website: 'https://kellogg.northwestern.edu' },
  { id: 112, title: 'Haas Summer', provider: 'Berkeley Haas', category: 'business', tags: ['Business', 'Entrepreneurship'], description: 'Haas programs.', cost: '$2,500+', website: 'https://haas.berkeley.edu' },
  { id: 113, title: 'Ross Summer', provider: 'Michigan Ross', category: 'business', tags: ['Business', 'Leadership'], description: 'Ross programs.', cost: '$3,000+', website: 'https://michiganross.umich.edu' },
  { id: 114, title: 'Tuck Summer', provider: 'Dartmouth Tuck', category: 'business', tags: ['Business', 'Residential'], description: 'Tuck programs.', cost: '$3,000+', website: 'https://tuck.dartmouth.edu' },
  { id: 115, title: 'Darden Summer', provider: 'UVA Darden', category: 'business', tags: ['Business', 'Case Method'], description: 'Darden programs.', cost: '$2,500+', website: 'https://darden.virginia.edu' },
  { id: 116, title: 'Yale Law', provider: 'Yale', category: 'business', tags: ['Law', 'Pre-Law'], description: 'Yale Law programs.', cost: '$2,500+', website: 'https://law.yale.edu' },
  { id: 117, title: 'Stanford in Washington', provider: 'Stanford', category: 'business', tags: ['Politics', 'DC'], description: 'Stanford in DC.', cost: '$3,000+', website: 'https://stanford.edu' },
  { id: 118, title: 'Georgetown Prep', provider: 'Georgetown', category: 'business', tags: ['Catholic', 'College Prep'], description: 'Prep programs.', cost: '$2,000+', website: 'https://georgetownprep.edu' },
  { id: 119, title: 'Columbia Business', provider: 'Columbia', category: 'business', tags: ['Business', 'Finance'], description: 'Columbia Business.', cost: '$3,000+', website: 'https://gsb.columbia.edu' },
  { id: 120, title: 'UC Davis', provider: 'UC Davis', category: 'stem', tags: ['STEM', 'Agriculture'], description: 'UC Davis programs.', cost: '$1,500+', website: 'https://ucdavis.edu' },
  { id: 121, title: 'UC Irvine', provider: 'UCI', category: 'stem', tags: ['Engineering', 'Computer Science'], description: 'UCI programs.', cost: '$1,500+', website: 'https://uci.edu' },
  { id: 122, title: 'UC Santa Barbara', provider: 'UCSB', category: 'summer', tags: ['STEM', 'Liberal Arts'], description: 'UCSB programs.', cost: '$1,500+', website: 'https://ucsb.edu' },
  { id: 123, title: 'UC San Diego', provider: 'UCSD', category: 'stem', tags: ['Engineering', 'Research'], description: 'UCSD programs.', cost: '$1,500+', website: 'https://ucsd.edu' },
  { id: 124, title: 'Arizona State', provider: 'ASU', category: 'summer', tags: ['Innovation', 'Entrepreneurship'], description: 'ASU programs.', cost: '$1,500+', website: 'https://asu.edu' },
  { id: 125, title: 'University of Colorado', provider: 'CU Boulder', category: 'stem', tags: ['Engineering', 'Physics'], description: 'CU programs.', cost: '$1,500+', website: 'https://colorado.edu' },
  { id: 126, title: 'University of Miami', provider: 'Miami', category: 'summer', tags: ['Marine Science', 'Sports'], description: 'Miami programs.', cost: '$2,000+', website: 'https://miami.edu' },
  { id: 127, title: 'University of Denver', provider: 'Denver', category: 'summer', tags: ['Outdoor', 'Leadership'], description: 'Denver programs.', cost: '$2,000+', website: 'https://du.edu' },
  { id: 128, title: 'University of Hawaii', provider: 'UH Manoa', category: 'summer', tags: ['Marine Science', 'Pacific'], description: 'Hawaii programs.', cost: '$2,000+', website: 'https://hawaii.edu' },
  { id: 129, title: 'University of Florida', provider: 'UF', category: 'stem', tags: ['Research', 'Engineering'], description: 'UF programs.', cost: '$1,500+', website: 'https://ufl.edu' },
  { id: 130, title: 'Penn State', provider: 'Penn State', category: 'summer', tags: ['Engineering', 'Business'], description: 'Penn State programs.', cost: '$2,000+', website: 'https://psu.edu' },
  { id: 131, title: 'Ohio State', provider: 'Ohio State', category: 'summer', tags: ['STEM', 'Sports'], description: 'Ohio State programs.', cost: '$1,500+', website: 'https://osu.edu' },
  { id: 132, title: 'University of Michigan', provider: 'UMich', category: 'stem', tags: ['Engineering', 'Research'], description: 'UMich programs.', cost: '$2,000+', website: 'https://umich.edu' },
  { id: 133, title: 'Georgia Tech', provider: 'Georgia Tech', category: 'stem', tags: ['Engineering', 'Coding'], description: 'GT programs.', cost: '$1,500+', website: 'https://gatech.edu' },
  { id: 134, title: 'Virginia Tech', provider: 'Virginia Tech', category: 'stem', tags: ['Engineering', 'STEM'], description: 'VT programs.', cost: '$1,500+', website: 'https://vt.edu' },
  { id: 135, title: 'University of Texas', provider: 'UT Austin', category: 'business', tags: ['Business', 'Engineering'], description: 'UT programs.', cost: '$1,500+', website: 'https://utexas.edu' },
  { id: 136, title: 'Northwestern', provider: 'Northwestern', category: 'summer', tags: ['Journalism', 'Debate'], description: 'Northwestern programs.', cost: '$3,000+', website: 'https://northwestern.edu' },
  { id: 137, title: 'WashU', provider: 'WashU', category: 'summer', tags: ['Research', 'Medicine'], description: 'WashU programs.', cost: '$2,500+', website: 'https://wustl.edu' },
  { id: 138, title: 'Johns Hopkins', provider: 'JHU', category: 'stem', tags: ['Research', 'Medicine'], description: 'JHU programs.', cost: '$2,500+', website: 'https://jhu.edu' },
  { id: 139, title: 'Rice', provider: 'Rice', category: 'summer', tags: ['STEM', 'Research'], description: 'Rice programs.', cost: '$2,000+', website: 'https://rice.edu' },
  { id: 140, title: 'Dartmouth', provider: 'Dartmouth', category: 'summer', tags: ['Liberal Arts', 'Writing'], description: 'Dartmouth programs.', cost: '$3,000+', website: 'https://dartmouth.edu' },
  { id: 141, title: 'Williams', provider: 'Williams', category: 'summer', tags: ['Liberal Arts', 'Math'], description: 'Williams programs.', cost: '$2,500+', website: 'https://williams.edu' },
  { id: 142, title: 'Amherst', provider: 'Amherst', category: 'summer', tags: ['Liberal Arts', 'Research'], description: 'Amherst programs.', cost: '$2,500+', website: 'https://amherst.edu' },
  { id: 143, title: 'Swarthmore', provider: 'Swarthmore', category: 'summer', tags: ['Liberal Arts', 'Engineering'], description: 'Swarthmore programs.', cost: '$2,000+', website: 'https://swarthmore.edu' },
  { id: 144, title: 'Middlebury', provider: 'Middlebury', category: 'writing', tags: ['Languages', 'Writing'], description: 'Middlebury programs.', cost: '$2,500+', website: 'https://middlebury.edu' },
  { id: 145, title: 'Carleton', provider: 'Carleton', category: 'stem', tags: ['STEM', 'Research'], description: 'Carleton programs.', cost: '$2,500+', website: 'https://carleton.edu' },
  { id: 146, title: 'Oberlin', provider: 'Oberlin', category: 'arts', tags: ['Music', 'Arts'], description: 'Oberlin programs.', cost: '$2,000+', website: 'https://oberlin.edu' },
  { id: 147, title: 'Vassar', provider: 'Vassar', category: 'summer', tags: ['Liberal Arts', 'Arts'], description: 'Vassar programs.', cost: '$2,500+', website: 'https://vassar.edu' },
  { id: 148, title: 'Wellesley', provider: 'Wellesley', category: 'summer', tags: ['Liberal Arts', 'Women'], description: 'Wellesley programs.', cost: '$2,500+', website: 'https://wellesley.edu' },
  { id: 149, title: 'Smith', provider: 'Smith College', category: 'summer', tags: ['Liberal Arts', 'Women'], description: 'Smith programs.', cost: '$2,500+', website: 'https://smith.edu' },
  { id: 150, title: 'Barnard', provider: 'Barnard', category: 'summer', tags: ['Liberal Arts', 'Women'], description: 'Barnard programs.', cost: '$2,500+', website: 'https://barnard.edu' },
  { id: 151, title: 'Bryn Mawr', provider: 'Bryn Mawr', category: 'summer', tags: ['Liberal Arts', 'Women'], description: 'Bryn Mawr programs.', cost: '$2,500+', website: 'https://brynmawr.edu' },
  { id: 152, title: 'Davidson Academy', provider: 'Davidson', category: 'stem', tags: ['Gifted', 'Highly Gifted'], description: 'Davidson Academy.', cost: '$1,500+', website: 'https://davidsonacademy.unr.edu' },
  { id: 153, title: 'Interlochen', provider: 'Interlochen', category: 'arts', tags: ['Arts', 'Music'], description: 'Interlochen programs.', cost: '$2,500+', website: 'https://interlochen.org' },
  { id: 154, title: 'Idyllwild Arts', provider: 'Idyllwild', category: 'arts', tags: ['Arts', 'Residential'], description: 'Idyllwild programs.', cost: '$2,500+', website: 'https://idyllwildarts.org' },
  { id: 155, title: 'Walnut Hill', provider: 'Walnut Hill', category: 'arts', tags: ['Arts', 'Performing'], description: 'Walnut Hill programs.', cost: '$3,000+', website: 'https://walnuthillart.org' },
  { id: 156, title: 'School of the Art Institute', provider: 'SAIC', category: 'arts', tags: ['Art', 'Design'], description: 'SAIC programs.', cost: '$2,500+', website: 'https://saic.edu' },
  { id: 157, title: 'Cooper Union', provider: 'Cooper Union', category: 'arts', tags: ['Art', 'Engineering'], description: 'Cooper Union.', cost: '$2,000+', website: 'https://cooper.edu' },
  { id: 158, title: 'Boston Architecture', provider: 'Boston Architecture', category: 'arts', tags: ['Architecture', 'Design'], description: 'Architecture programs.', cost: '$2,500+', website: 'https://bu.edu' },
  { id: 159, title: 'Cincinnati Arts', provider: 'Cincinnati', category: 'arts', tags: ['Arts', 'Design'], description: 'Cincinnati programs.', cost: '$2,000+', website: 'https://cincinnatiarts.org' },
  { id: 160, title: 'SUNY Purchase', provider: 'SUNY Purchase', category: 'arts', tags: ['Arts', 'Music'], description: 'Purchase programs.', cost: '$1,500+', website: 'https://purchase.edu' },
  { id: 161, title: 'Savannah College Art', provider: 'SCAD', category: 'arts', tags: ['Film', 'Game Design'], description: 'SCAD programs.', cost: '$2,000+', website: 'https://scad.edu' },
  { id: 162, title: 'Ringling College', provider: 'Ringling', category: 'arts', tags: ['Animation', 'Film'], description: 'Ringling programs.', cost: '$2,000+', website: 'https://ringling.edu' },
  { id: 163, title: 'Full Sail University', provider: 'Full Sail', category: 'arts', tags: ['Film', 'Game Design'], description: 'Full Sail programs.', cost: '$2,000+', website: 'https://fullsail.edu' },
  { id: 164, title: 'Academy of Art', provider: 'Academy of Art', category: 'arts', tags: ['Art', 'Fashion'], description: 'Academy programs.', cost: '$2,000+', website: 'https://academyart.edu' },
  { id: 165, title: 'Peloton', provider: 'Peloton', category: 'stem', tags: ['Fitness', 'Tech'], description: 'Peloton programs.', cost: 'Paid', website: 'https://onepeloton.com' },
  { id: 166, title: 'SoulCycle', provider: 'SoulCycle', category: 'stem', tags: ['Fitness', 'Wellness'], description: 'SoulCycle instructor.', cost: 'Paid', website: 'https://soul-cycle.com' },
  { id: 167, title: 'CrossFit', provider: 'CrossFit', category: 'stem', tags: ['Fitness', 'Sports'], description: 'CrossFit programs.', cost: 'Paid', website: 'https://crossfit.com' },
  { id: 168, title: 'Yoga', provider: 'Yoga Alliance', category: 'stem', tags: ['Wellness', 'Fitness'], description: 'Yoga teacher training.', cost: 'Paid', website: 'https://yogaalliance.org' },
  { id: 169, title: 'Barre', provider: 'Barre', category: 'stem', tags: ['Fitness', 'Dance'], description: 'Barre instructor.', cost: 'Paid', website: 'https://barre3.com' },
  { id: 170, title: 'Pilates', provider: 'Pilates', category: 'stem', tags: ['Fitness', 'Core'], description: 'Pilates instructor.', cost: 'Paid', website: 'https://pilates.com' },
  { id: 171, title: 'Meditation', provider: 'Headspace', category: 'stem', tags: ['Wellness', 'Mental Health'], description: 'Meditation training.', cost: 'Paid', website: 'https://headspace.com' },
  { id: 172, title: 'Nutrition', provider: 'Precision Nutrition', category: 'stem', tags: ['Health', 'Wellness'], description: 'Nutrition coaching.', cost: 'Paid', website: 'https://precisionnutrition.com' },
  { id: 173, title: 'Personal Training', provider: 'NASM', category: 'stem', tags: ['Fitness', 'Training'], description: 'Personal trainer cert.', cost: 'Paid', website: 'https://nasm.org' },
  { id: 174, title: 'Swimming', provider: 'American Swim', category: 'stem', tags: ['Sports', 'Aquatics'], description: 'Swim instruction.', cost: 'Paid', website: 'https://americanswim.org' },
  { id: 175, title: 'Tennis', provider: 'USTA', category: 'stem', tags: ['Sports', 'Tennis'], description: 'Tennis coaching.', cost: 'Paid', website: 'https://usta.com' },
  { id: 176, title: 'Golf', provider: 'PGA', category: 'stem', tags: ['Sports', 'Golf'], description: 'Golf instruction.', cost: 'Paid', website: 'https://pgaprogram.org' },
  { id: 177, title: 'Martial Arts', provider: 'USKA', category: 'stem', tags: ['Sports', 'Martial Arts'], description: 'Martial arts training.', cost: 'Paid', website: 'https://uska.org' },
  { id: 178, title: 'Dance', provider: 'Broadway Dance', category: 'arts', tags: ['Dance', 'Performance'], description: 'Dance programs.', cost: 'Paid', website: 'https://broadwaydancecenter.com' },
  { id: 179, title: 'Photography', provider: 'Photography', category: 'arts', tags: ['Visual Arts', 'Media'], description: 'Photography courses.', cost: 'Paid', website: 'https://precision-camera.com' },
  { id: 180, title: 'Cooking', provider: 'Culinary Institute', category: 'stem', tags: ['Culinary', 'Food'], description: 'Culinary programs.', cost: 'Paid', website: 'https://ciachef.edu' },
  { id: 181, title: 'Baking', option: 'Pastry Arts', category: 'stem', tags: ['Culinary', 'Baking'], description: 'Baking programs.', cost: 'Paid', website: 'https://pastryarts.org' },
  { id: 182, title: 'Sommelier', provider: 'Wine School', category: 'stem', tags: ['Wine', 'Hospitality'], description: 'Wine certification.', cost: 'Paid', website: 'https://wineschool.org' },
  { id: 183, title: 'Bartending', provider: 'USBA', category: 'stem', tags: ['Hospitality', 'Service'], description: 'Bartending school.', cost: 'Paid', website: 'https://usba.org' },
  { id: 184, title: 'Hotel Management', provider: 'Cornell SC Johnson', category: 'business', tags: ['Hospitality', 'Business'], description: 'Hotel management.', cost: 'Paid', website: 'https://sha.cornell.edu' },
  { id: 185, title: 'Travel Management', provider: 'Travel Institute', category: 'business', tags: ['Travel', 'Hospitality'], description: 'Travel agent cert.', cost: 'Paid', website: 'https://travelinstitute.com' },
  { id: 186, title: 'Real Estate', provider: 'NAR', category: 'business', tags: ['Real Estate', 'Sales'], description: 'Real estate license.', cost: 'Paid', website: 'https://nar.org' },
  { id: 187, title: 'Insurance', provider: 'CII', category: 'business', tags: ['Finance', 'Insurance'], description: 'Insurance licensing.', cost: 'Paid', website: 'https://cii.org' },
  { id: 188, title: 'Financial Planning', provider: 'CFP', category: 'business', tags: ['Finance', 'Planning'], description: 'Financial planning cert.', cost: 'Paid', website: 'https://cfp.net' },
  { id: 189, title: 'Banking', provider: 'Institute of Banking', category: 'business', tags: ['Finance', 'Banking'], description: 'Banking certification.', cost: 'Paid', website: 'https://bankersacademy.org' },
  { id: 190, title: 'Fashion Design', provider: 'FIT', category: 'arts', tags: ['Fashion', 'Design'], description: 'Fashion design.', cost: 'Paid', website: 'https://fitnyc.edu' },
  { id: 191, title: 'Interior Design', provider: 'NYIAD', category: 'arts', tags: ['Design', 'Interior'], description: 'Interior design.', cost: 'Paid', website: 'https://nyiad.edu' },
  { id: 192, title: 'Graphic Design', provider: 'AIGA', category: 'arts', tags: ['Design', 'Visual'], description: 'Graphic design.', cost: 'Paid', website: 'https://aiga.org' },
  { id: 193, title: 'Web Design', provider: 'General Assembly', category: 'coding', tags: ['Design', 'Web Dev'], description: 'Web design courses.', cost: 'Paid', website: 'https://generalassemb.ly' },
  { id: 194, title: 'UX Design', provider: 'Google UX', category: 'coding', tags: ['Design', 'User Experience'], description: 'UX certification.', cost: 'Paid', website: 'https://uxdesign.org' },
  { id: 195, title: 'Product Design', provider: 'PDI', category: 'coding', tags: ['Design', 'Product'], description: 'Product design.', cost: 'Paid', website: 'https://productdesign.org' },
  { id: 196, title: 'Game Design', provider: 'Game Design', category: 'coding', tags: ['Gaming', 'Design'], description: 'Game design.', cost: 'Paid', website: 'https://gamedesign.org' },
  { id: 197, title: 'Animation', provider: 'Animation Guild', category: 'arts', tags: ['Animation', 'Film'], description: 'Animation training.', cost: 'Paid', website: 'https://animationguild.org' },
  { id: 198, title: 'VFX', provider: 'VFX', category: 'arts', tags: ['Film', 'Visual Effects'], description: 'VFX courses.', cost: 'Paid', website: 'https://visualeffectssociety.com' },
  { id: 199, title: 'Sound Engineering', provider: 'Audio Engineering', category: 'arts', tags: ['Music', 'Recording'], description: 'Audio engineering.', cost: 'Paid', website: 'https://aes.org' },
  { id: 200, title: 'DJ Training', provider: 'Dubspot', category: 'arts', tags: ['Music', 'DJ'], description: 'DJ courses.', cost: 'Paid', website: 'https://dubspot.edu' },
  { id: 201, title: 'Music Production', provider: 'Berklee Online', category: 'arts', tags: ['Music', 'Production'], description: 'Music production.', cost: 'Paid', website: 'https://online.berklee.edu' },
  { id: 202, title: 'Voice Acting', provider: 'Voice Acting', category: 'arts', tags: ['Voice', 'Performance'], description: 'Voice acting.', cost: 'Paid', website: 'https://gvaw.org' },
  { id: 203, title: 'Acting', provider: 'Acting', category: 'arts', tags: ['Drama', 'Performance'], description: 'Acting classes.', cost: 'Paid', website: 'https://actorsstudio.org' },
  { id: 204, title: 'Screenwriting', provider: 'WGA', category: 'writing', tags: ['Film', 'Screenplay'], description: 'Screenwriting.', cost: 'Paid', website: 'https://wgawrest.org' },
  { id: 205, title: 'Journalism', provider: 'Journalism School', category: 'writing', tags: ['Media', 'News'], description: 'Journalism degree.', cost: 'Paid', website: 'https://journalism.org' },
  { id: 206, title: 'Public Relations', provider: 'PRSSA', category: 'business', tags: ['Communications', 'Media'], description: 'PR certification.', cost: 'Paid', website: 'https://prssa.org' },
  { id: 207, title: 'Marketing', provider: 'AMA', category: 'business', tags: ['Marketing', 'Digital'], description: 'Marketing cert.', cost: 'Paid', website: 'https://ama.org' },
  { id: 208, title: 'Social Media', provider: 'Hootsuite', category: 'business', tags: ['Marketing', 'Social Media'], description: 'Social media marketing.', cost: 'Paid', website: 'https://hootsuite.com' },
  { id: 209, title: 'SEO', provider: 'Moz', category: 'coding', tags: ['Marketing', 'Search'], description: 'SEO training.', cost: 'Paid', website: 'https://moz.com' },
  { id: 210, title: 'Data Science', provider: 'Data Science', category: 'coding', tags: ['Data', 'Analytics'], description: 'Data science bootcamp.', cost: 'Paid', website: 'https://datascience.org' },
  { id: 211, title: 'Machine Learning', provider: 'Fast.ai', category: 'coding', tags: ['AI', 'Deep Learning'], description: 'ML courses.', cost: 'Free', website: 'https://fast.ai' },
  { id: 212, title: 'Cybersecurity', provider: '(ISC)2', category: 'coding', tags: ['Security', 'IT'], description: 'Cybersecurity cert.', cost: 'Paid', website: 'https://isc2.org' },
  { id: 213, title: 'Cloud Computing', provider: 'AWS', category: 'coding', tags: ['Cloud', 'Tech'], description: 'AWS training.', cost: 'Paid', website: 'https://aws.amazon.com' },
  { id: 214, title: 'DevOps', provider: 'DevOps', category: 'coding', tags: ['Engineering', 'Automation'], description: 'DevOps training.', cost: 'Paid', website: 'https://devops.com' },
  { id: 215, title: 'Blockchain', provider: 'Blockchain', category: 'coding', tags: ['Crypto', 'Web3'], description: 'Blockchain training.', cost: 'Paid', website: 'https://blockchain.com' },
  { id: 216, title: 'Project Management', provider: 'PMI', category: 'business', tags: ['Management', 'Leadership'], description: 'PMP certification.', cost: 'Paid', website: 'https://pmi.org' },
  { id: 217, title: 'Scrum Master', provider: 'Scrum Alliance', category: 'business', tags: ['Agile', 'Management'], description: 'Scrum certification.', cost: 'Paid', website: 'https://scrumalliance.org' },
  { id: 218, title: 'Six Sigma', provider: 'ASQ', category: 'business', tags: ['Quality', 'Management'], description: 'Six Sigma training.', cost: 'Paid', website: 'https://asq.org' },
  { id: 219, title: 'HR', provider: 'SHRM', category: 'business', tags: ['Human Resources', 'Management'], description: 'HR certification.', cost: 'Paid', website: 'https://shrm.org' },
  { id: 220, title: 'Teaching', provider: 'Teaching', category: 'free', tags: ['Education', 'Career'], description: 'Teaching credential.', cost: 'Paid', website: 'https://teaching.com' },
  { id: 221, title: 'Coaching', provider: 'ICF', category: 'business', tags: ['Coaching', 'Leadership'], description: 'Life coaching.', cost: 'Paid', website: 'https://coachingfederation.org' },
  { id: 222, title: 'Consulting', provider: 'Consulting', category: 'business', tags: ['Strategy', 'Management'], description: 'Consulting training.', cost: 'Paid', website: 'https://consulting.com' },
  { id: 223, title: 'Architecture', provider: 'AIA', category: 'arts', tags: ['Design', 'Building'], description: 'Architecture license.', cost: 'Paid', website: 'https://aia.org' },
  { id: 224, title: 'Landscape Architecture', provider: 'ASLA', category: 'arts', tags: ['Design', 'Environment'], description: 'Landscape architecture.', cost: 'Paid', website: 'https://asla.org' },
  { id: 225, title: 'Urban Planning', provider: 'APA', category: 'business', tags: ['Planning', 'City Design'], description: 'Urban planning.', cost: 'Paid', website: 'https://planning.org' },
  { id: 226, title: 'Civil Engineering', provider: 'ASCE', category: 'stem', tags: ['Engineering', 'Construction'], description: 'Civil engineering.', cost: 'Paid', website: 'https://asce.org' },
  { id: 227, title: 'Mechanical Engineering', provider: 'ASME', category: 'stem', tags: ['Engineering', 'Machines'], description: 'Mechanical engineering.', cost: 'Paid', website: 'https://asme.org' },
  { id: 228, title: 'Electrical Engineering', provider: 'IEEE', category: 'stem', tags: ['Engineering', 'Electronics'], description: 'Electrical engineering.', cost: 'Paid', website: 'https://ieee.org' },
  { id: 229, title: 'Chemical Engineering', provider: 'AIChE', category: 'stem', tags: ['Engineering', 'Chemistry'], description: 'Chemical engineering.', cost: 'Paid', website: 'https://aiche.org' },
  { id: 230, title: 'Biomedical Engineering', provider: 'BMES', category: 'stem', tags: ['Engineering', 'Medicine'], description: 'Biomedical programs.', cost: 'Paid', website: 'https://bmes.org' },
  { id: 231, title: 'Aerospace Engineering', provider: 'AIAA', category: 'stem', tags: ['Engineering', 'Space'], description: 'Aerospace programs.', cost: 'Paid', website: 'https://aiaa.org' },
  { id: 232, title: 'Marine Engineering', provider: 'Marine Engineering', category: 'stem', tags: ['Engineering', 'Ocean'], description: 'Marine programs.', cost: 'Paid', website: 'https://marine-engineering.org' },
  { id: 233, title: 'Environmental Engineering', provider: 'AAEE', category: 'stem', tags: ['Engineering', 'Environment'], description: 'Environmental programs.', cost: 'Paid', website: 'https://aaee.net' },
  { id: 234, title: 'Industrial Engineering', provider: 'IIE', category: 'stem', tags: ['Engineering', 'Operations'], description: 'Industrial programs.', cost: 'Paid', website: 'https://iienet.org' },
  { id: 235, title: 'Materials Science', provider: 'Materials Science', category: 'research', tags: ['Engineering', 'Science'], description: 'Materials science.', cost: 'Paid', website: 'https://materialsscience.org' },
  { id: 236, title: 'Nanotechnology', provider: 'Nanotech', category: 'stem', tags: ['Science', 'Nano'], description: 'Nanotech courses.', cost: 'Paid', website: 'https://nanotech.org' },
  { id: 237, title: 'Biotechnology', provider: 'Biotech', category: 'stem', tags: ['Biology', 'Tech'], description: 'Biotech training.', cost: 'Paid', website: 'https://biotechcareers.org' },
  { id: 238, title: 'Genetics', provider: 'Genetics', category: 'stem', tags: ['Biology', 'Research'], description: 'Genetics programs.', cost: 'Paid', website: 'https://genetics.edu' },
  { id: 239, title: 'Neuroscience', provider: 'Neuroscience', category: 'stem', tags: ['Brain', 'Research'], description: 'Neuroscience courses.', cost: 'Paid', website: 'https://neuroscience.org' },
  { id: 240, title: 'Psychology', provider: 'APA', category: 'stem', tags: ['Mind', 'Science'], description: 'Psychology degree.', cost: 'Paid', website: 'https://apa.org' },
  { id: 241, title: 'Sociology', provider: 'Sociology', category: 'stem', tags: ['Society', 'Research'], description: 'Sociology programs.', cost: 'Paid', website: 'https://asanet.org' },
  { id: 242, title: 'Anthropology', provider: 'Anthropology', category: 'stem', tags: ['Culture', 'Research'], description: 'Anthro courses.', cost: 'Paid', website: 'https://americananthro.org' },
  { id: 243, title: 'Economics', provider: 'Economics', category: 'business', tags: ['Finance', 'Theory'], description: 'Economics degree.', cost: 'Paid', website: 'https://aeaweb.org' },
  { id: 244, title: 'Political Science', provider: 'PoliSci', category: 'business', tags: ['Politics', 'Government'], description: 'PoliSci courses.', cost: 'Paid', website: 'https://apsa.org' },
  { id: 245, title: 'International Relations', provider: 'IR', category: 'business', tags: ['Diplomacy', 'Global'], description: 'IR programs.', cost: 'Paid', website: 'https://cirweb.org' },
  { id: 246, title: 'Philosophy', provider: 'Philosophy', category: 'writing', tags: ['Think', 'Logic'], description: 'Philosophy courses.', cost: 'Paid', website: 'https://philosophers.net' },
  { id: 247, title: 'History', provider: 'History', category: 'writing', tags: ['Past', 'Research'], description: 'History degree.', cost: 'Paid', website: 'https://historians.org' },
  { id: 248, title: 'Geography', provider: 'Geography', category: 'stem', tags: ['Maps', 'Environment'], description: 'Geography courses.', cost: 'Paid', website: 'https://aag.org' },
  { id: 249, title: 'Archaeology', provider: 'Archaeology', category: 'research', tags: ['History', 'Excavation'], description: 'Archaeology courses.', cost: 'Paid', website: 'https://archaeological.org' },
  { id: 250, title: 'Linguistics', provider: 'Linguistics', category: 'writing', tags: ['Language', 'Communication'], description: 'Linguistics courses.', cost: 'Paid', website: 'https://linguistlist.org' },

  // Research Programs
  { id: 251, title: 'MIT RSI', provider: 'MIT', category: 'research', tags: ['Research', 'STEM', 'Prestigious'], description: 'Premier summer research program at MIT.', cost: 'Free', website: 'https://www.esp.org' },
  { id: 252, title: 'SSP', provider: 'Summer Science Program', category: 'research', tags: ['Research', 'STEM', 'Residential'], description: 'Research in astrophysics or biochemistry.', cost: 'Paid', website: 'https://summerscience.org' },
  { id: 253, title: 'Carnegie Mellon S3', provider: 'CMU', category: 'research', tags: ['Research', 'STEM', 'Intro'], description: 'Summer Session for Students.', cost: 'Paid', website: 'https://cmu.edu' },
  { id: 254, title: 'Clark Scholars', provider: 'Clark Scholar', category: 'research', tags: ['Research', 'STEM', 'Free'], description: 'Free research program for high school students.', cost: 'Free', website: 'https://clarkscholars.org' },
  { id: 255, title: 'Simons Summer Research', provider: 'Stony Brook', category: 'research', tags: ['Research', 'STEM', 'Long Island'], description: 'Authentic research experience.', cost: 'Paid', website: 'https://stonybrook.edu' },

  // Sports Programs
  { id: 256, title: 'Nike Basketball Camp', provider: 'Nike', category: 'sports', tags: ['Basketball', 'Athletics', 'Summer'], description: 'Elite basketball training.', cost: 'Paid', website: 'https://nike.com' },
  { id: 257, title: 'IMG Academy', provider: 'IMG', category: 'sports', tags: ['Multi-Sport', 'Athletics', 'Residential'], description: 'World-class sports training.', cost: 'Paid', website: 'https://imgacademy.com' },
  { id: 258, title: 'US Sports Camps', provider: 'USSC', category: 'sports', tags: ['Multi-Sport', 'Coaching'], description: 'Sports camps nationwide.', cost: 'Paid', website: 'https://ussportscamps.com' },
  { id: 259, title: 'Under Armour', provider: 'Under Armour', category: 'sports', tags: ['Basketball', 'Baseball', 'Training'], description: 'UA basketball and baseball camps.', cost: 'Paid', website: 'https://underarmour.com' },
  { id: 260, title: 'ESPN Sports Academy', provider: 'ESPN', category: 'sports', tags: ['Sports Media', 'Broadcasting'], description: 'Sports broadcasting and media.', cost: 'Paid', website: 'https://espn.com' },

  // Music Programs
  { id: 261, title: 'Berklee Summer', provider: 'Berklee College', category: 'music', tags: ['Music', 'Performance', 'College'], description: 'Music performance and production.', cost: 'Paid', website: 'https://berklee.edu' },
  { id: 262, title: 'Juilliard Pre-College', provider: 'Juilliard', category: 'music', tags: ['Music', 'Prestigious', 'Performance'], description: 'Pre-college conservatory training.', cost: 'Paid', website: 'https://juilliard.edu' },
  { id: 263, title: 'New England Conservatory', provider: 'NEC', category: 'music', tags: ['Music', 'Classical', 'Performance'], description: 'Classical music training.', cost: 'Paid', website: 'https://necmusic.edu' },
  { id: 264, title: 'Yamaha Music', provider: 'Yamaha', category: 'music', tags: ['Music', 'Instruments', 'Online'], description: 'Online music lessons.', cost: 'Paid', website: 'https://yamaha.com' },
  { id: 265, title: 'Bands of America', provider: 'BOA', category: 'music', tags: ['Music', 'Marching Band', 'Competition'], description: 'Marching band competitions.', cost: 'Paid', website: 'https://bandsamerica.org' },
];
